default:
  image: ubuntu:latest

.pre:
  stage: .pre
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Berlin apt-get install -y gcc g++ make cmake git

build:
  stage: build
  script:
    - mkdir build
    - cmake -H. -Bbuild
    - cd build && cmake --build .

test:
  stage: test
  script:
    - ctest --extra-verbose
